### ISSUE TITLE
Understand Methodology

### ISSUE THREAD

**Issue by xinshizheng** [California-Data-Collaborative/Evapotranspiration#2]
Hart, Q. J., Brugnach, M., Temesgen, B., Rueda, C., Ustin, S. L., & Frame, K. (2009). Daily reference evapotranspiration for California using satellite imagery and weather station measurement interpolation. Civil engineering and environmental systems, 26(1), 19-33.

Snyder, R. L. (2005). The ASCE standardized reference evapotranspiration equation. Technical Committee report to the Environmental and Water Resources Institute of the American Society of Civil Engineers from the Task Committee on Standardization of Reference Evapotranspiration, 173.

**Comment by patwater** [comment]
Great!  Also the State's CIMIS webpage has lots of great information: http://www.cimis.water.ca.gov/Resources.aspx

**Comment by patwater** [comment]
@xinshizheng @overwaterland any questions for @gcortesla or myself?

**Comment by xinshizheng** [comment]
@patwater @gcortesla 
The methodology in the first paper is quite comprehensive. I want to summarize what we should do next. Basically we want to use higher resolution data to either replace or supplement the CIMIS station sensor data for weather parameters in the model, namely daily min, max air temperature and dew point temperature at 1.5 m, and wind speed at 2 m as model input (standard condition). We first want to identify potential data sources of relevant parameters and then may try to convert them to the standard condition. Second, depending on the nature of the new weather data, spatial interpolation may need to be applied according to the land cover/physiographic data. Finally, combine the new weather data with solar radiation data to compute ET0 for every 2km cell. Let me know if my interpretation is wrong.

Besides, one question regarding the methodology. On page number 24 the paper says 'These values are calculated hourly from sunrise until sunset for every day'. So we don't consider evapotranspiration at night?

**Comment by gcortesla** [comment]
@xinshizheng we want to supplement the existing CIMIS data (not replace), and your description of the objective is correct. Ideally we would like a better resolution than 2 km (maybe in the order of 100s of meters), as 2 km is not very useful for urban settings. 

ET at night is negligible (i.e., plants don't perform any photosynthetic activity).

**Comment by xinshizheng** [comment]
Thanks @gcortesla . Your explanation is very helpful.

**Comment by tylere** [comment]
While transpiration shuts down at night, the evaporation component of ET can be significant, particularly for arid windy areas.
Example ref: http://www.sciencedirect.com/science/article/pii/002216949290159S

**Comment by gcortesla** [comment]
Indeed. Might be relevant for some farming areas in the California desert.
